from google import genai
from dotenv import load_dotenv
import os

from .prompt import SYSTEM_PROMPT

load_dotenv(".env.local")

client = genai.Client(
api_key=os.getenv("GEMINI_API_KEY")
)


BUS_ROUTES = {
    "21": {
        "vehicle_no": "TN 22 BS 3669",
        "driver_name": "B. Kutty",
        "driver_phone": "63798 86625",
        "stops": [
            ("Pallavaram - Yard", "6:15 AM"),
            ("Chennai One, Kamatchi", "6:20 AM"),
            ("Hospital", "6:25 AM"),
            ("Kovilambakkam", "6:40 AM"),
            ("Echangadu Signal", "6:45 AM"),
            ("Pallavaram Gadu", "6:47 AM"),
            ("Hasthinapuram", "6:58 AM"),
            ("Sanitorium, Gandhi Road", "7:05 AM"),
            ("Krishna Nagar", "7:10 AM"),
            ("Bharathi Nagar", "7:20 AM"),
            ("Mudichur", "7:30 AM"),
            ("Manivakkam Junction", "7:35 AM"),
            ("Padappai", "7:45 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "22": {
        "vehicle_no": "TN 23 J 1653",
        "driver_name": "Devaraj P.",
        "driver_phone": "98417 85153",
        "stops": [
            ("VGP", "5:45 AM"),
            ("Injambakkam Signal", "5:50 AM"),
            ("Vettuvangani", "5:55 AM"),
            ("Palavakkam", "5:57 AM"),
            ("Kottivakkam", "6:00 AM"),
            ("Thiruvanmiyur RTO", "6:02 AM"),
            ("Thiruvanmiyur Signal", "6:05 AM"),
            ("Taramani", "6:08 AM"),
            ("Madhya Kailash", "6:10 AM"),
            ("SRP Tools", "6:15 AM"),
            ("Baby Nagar", "6:20 AM"),
            ("Vijaya Nagar Bus Stand", "6:22 AM"),
            ("Adambakkam Railway Station", "6:25 AM"),
            ("Pallikaranai", "6:45 AM"),
            ("Jayachandran Tex", "6:55 AM"),
            ("Medavakkam Junction", "7:00 AM"),
            ("Santhoshpuram", "7:05 AM"),
            ("Gowrivakkam", "7:07 AM"),
            ("Chembakkam", "7:10 AM"),
            ("Kamarajar Puram", "7:12 AM"),
            ("Raja Keelpakkam", "7:15 AM"),
            ("Camp Road", "7:17 AM"),
            ("Selaiyur Police Station", "7:20 AM"),
            ("Tambaram MCC", "7:25 AM"),
            ("College", "8:00 AM"),
        ],
    },
    "23": {
        "vehicle_no": "TN 22 BS 4250",
        "driver_name": "Jaikar E.",
        "driver_phone": "98412 51747",
        "stops": [
            ("Ennore - Parking", "5:20 AM"),
            ("IOC", "5:50 AM"),
            ("Power House Bridge", "5:53 AM"),
            ("Korukkupet", "5:55 AM"),
            ("Basin Bridge, Pulianthope", "6:15 AM"),
            ("Chekli Palayam (Jamaliya)", "6:18 AM"),
            ("Otteri Police Station", "6:20 AM"),
            ("Aynavaram", "6:25 AM"),
            ("ICF", "6:27 AM"),
            ("New Avadi Road", "6:30 AM"),
            ("Villivakkam - Nathamuni", "6:35 AM"),
            ("Padi Bridge", "6:37 AM"),
            ("Thirumangalam", "6:40 AM"),
            ("Mugappair - Golden Flats", "6:45 AM"),
            ("Vaduvankarai Bridge", "6:50 AM"),
            ("Maduravoyal - Ration Store", "6:55 AM"),
            ("Maduravoyal - Toll Gate", "6:57 AM"),
            ("Perungalathur", "7:30 AM"),
            ("Manivakkam", "7:45 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "24": {
        "vehicle_no": "TN 11 F 0286",
        "driver_name": "Muniyandi",
        "driver_phone": "96772 94282",
        "stops": [
            ("Ennore Parking, Netaji Nagar", "5:40 AM"),
            ("Bharathiyar Nagar", "5:42 AM"),
            ("Patnathar Kovil", "5:45 AM"),
            ("Vannarapet Beach Kovil", "5:50 AM"),
            ("Kasimedu, Kalmandapam", "5:55 AM"),
            ("Royapuram Signal", "6:00 AM"),
            ("Royapuram Bridge", "6:02 AM"),
            ("Tambuchetty Street", "6:05 AM"),
            ("Stanley Hospital, Mint Bus Stop", "6:10 AM"),
            ("Bharathi Arts College", "6:12 AM"),
            ("Muthyalpet Police Station", "6:14 AM"),
            ("Mannadi, High Court Metro", "6:15 AM"),
            ("Thalamai Sailagam Metro", "6:17 AM"),
            ("Mount Road, Mosque", "6:20 AM"),
            ("Police Station, Whites Road", "6:25 AM"),
            ("Thousand Lights Church", "6:27 AM"),
            ("Park Vanavil, Saidapet", "6:30 AM"),
            ("Guindy, Alandur Metro", "6:35 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "25": {
        "vehicle_no": "TN 11 F 0076",
        "driver_name": "Udhayakumar B.",
        "driver_phone": "98408 23701",
        "stops": [
            ("K.V.T. Parking Yard", "5:30 AM"),
            ("M.R. Nagar", "5:40 AM"),
            ("Kannadasan Nagar - EB", "5:43 AM"),
            ("Bharathi Nagar", "5:45 AM"),
            ("Ambedkar College", "5:50 AM"),
            ("B.B. Road", "5:52 AM"),
            ("Jamaliya", "5:55 AM"),
            ("Chekili Palayam", "6:00 AM"),
            ("Purasaivakkam", "6:10 AM"),
            ("Periamet, G.1 Police Station", "6:15 AM"),
            ("Daily Thanthi Office", "6:17 AM"),
            ("Egmore (Back Side)", "6:20 AM"),
            ("Das Prakash Hotel", "6:25 AM"),
            ("Sangam Theatre", "6:30 AM"),
            ("EGA Theatre", "6:33 AM"),
            ("Sky Walk", "6:40 AM"),
            ("Arumbakkam, MMDA", "6:45 AM"),
            ("Lakshman Sruthi, Vadapalani", "6:50 AM"),
            ("Kasi Theatre, Zaparkhan Pettai", "6:54 AM"),
            ("Shanthi Petrol Bunk (Opp. Airport)", "7:00 AM"),
            ("Pallavaram, Amma Hotel", "7:10 AM"),
            ("Saravana Stores, Chrompet", "7:25 AM"),
            ("Tambaram", "7:25 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "26": {
        "vehicle_no": "TN 11 F 0258",
        "driver_name": "Manikandan T.",
        "driver_phone": "91760 46241",
        "stops": [
            ("Jothi Nagar", "5:30 AM"),
            ("Manali", "5:40 AM"),
            ("Mathur - MMDA", "5:43 AM"),
            ("Mathur Gate", "5:45 AM"),
            ("Thapal Petti", "5:50 AM"),
            ("Moola Kadai", "5:55 AM"),
            ("Shell Petrol Bunk", "6:00 AM"),
            ("Madhavaram", "6:10 AM"),
            ("Rettari", "6:25 AM"),
            ("Senthil Nagar", "6:35 AM"),
            ("Koyambedu", "6:40 AM"),
            ("Vadapalani", "6:42 AM"),
            ("Ashok Pillar", "6:45 AM"),
            ("Kasi Theatre", "6:52 AM"),
            ("Ekkatuthangal Metro", "6:57 AM"),
            ("Alandur Metro", "7:00 AM"),
            ("Alandur Court", "7:03 AM"),
            ("Shanthi Petrol Bunk", "7:07 AM"),
            ("Chrompet", "7:20 AM"),
            ("Tambaram Sanatorium", "7:26 AM"),
            ("Tambaram", "7:30 AM"),
            ("Vandalur Bridge", "7:38 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "28": {
        "vehicle_no": "TN 11 F 0266",
        "driver_name": "Palani S.",
        "driver_phone": "63822 06921",
        "stops": [
            ("Avadi - Yard", "5:45 AM"),
            ("Avadi - Check Post", "5:50 AM"),
            ("J.B. Estate", "6:05 AM"),
            ("Paruthipet", "6:10 AM"),
            ("Kumananchavadi", "6:20 AM"),
            ("Mangadu", "6:25 AM"),
            ("Pattur", "6:35 AM"),
            ("Four Roads, Kollacheri", "6:40 AM"),
            ("Kundrathur", "6:45 AM"),
            ("Kundrathur Bypass", "6:47 AM"),
            ("Thirumudivakkam Bypass", "7:00 AM"),
            ("Mannivakkam", "7:20 AM"),
            ("Padappai", "7:45 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "29": {
        "vehicle_no": "TN 11 T 9910",
        "driver_name": "Balamurugan",
        "driver_phone": "86103 78819",
        "stops": [
            ("Parking Yard", "6:10 AM"),
            ("Oli Mohammedpettai", "6:20 AM"),
            ("Kamalatheru", "6:25 AM"),
            ("Pookadai Chathiram", "6:27 AM"),
            ("Moongil Mandabam", "6:30 AM"),
            ("Keerai Mandabam", "6:32 AM"),
            ("Sevilimedu", "6:40 AM"),
            ("Indhra Petrol Bunk", "6:45 AM"),
            ("Bus Stand", "6:55 AM"),
            ("Rangasami Kulam", "7:00 AM"),
            ("Periyar Nagar - Toll Gate", "7:05 AM"),
            ("Periyar Nagar", "7:07 AM"),
            ("Ayyampettai", "7:10 AM"),
            ("Rajam Pettai", "7:20 AM"),
            ("Walajabad", "7:25 AM"),
            ("Vanravasi", "7:35 AM"),
            ("Oragadam Junction", "7:50 AM"),
            ("Karanithangal", "7:55 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "30": {
        "vehicle_no": "TN 11 T 9820",
        "driver_name": "S. Janakiraman",
        "driver_phone": "95786 16178",
        "stops": [
            ("CSI School Yard", "6:15 AM"),
            ("ITI, Collector Office (New)", "6:40 AM"),
            ("Pillayar Koil, Collector Office", "6:45 AM"),
            ("G.H. Hospital", "6:48 AM"),
            ("Rattina Kinaru", "6:50 AM"),
            ("Vedachalam Nagar", "6:53 AM"),
            ("Chengalpattu New Bus Stand", "6:55 AM"),
            ("Chengalpattu Old Bus Stand", "7:00 AM"),
            ("JSP Hospital", "7:03 AM"),
            ("Ayyappan Kovil", "7:05 AM"),
            ("Paranur", "7:10 AM"),
            ("Thirtheri Bus Stand", "7:15 AM"),
            ("S.P. Koil", "7:20 AM"),
            ("Ford Company", "7:22 AM"),
            ("Maraimalai Nagar", "7:25 AM"),
            ("Kattankulathur", "7:30 AM"),
            ("SRM University", "7:32 AM"),
            ("Thailavaram", "7:35 AM"),
            ("Guduvancherry Bus Stand", "7:37 AM"),
            ("Manivakkam", "7:50 AM"),
            ("Padappai", "8:00 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "31": {
        "vehicle_no": "TN 11 T 9808",
        "driver_name": "Balaji K.",
        "driver_phone": "98403 06310",
        "stops": [
            ("AVR - Parking Yard", "5:30 AM"),
            ("Konimedu", "5:40 AM"),
            ("Padianallur", "6:00 AM"),
            ("Red Hills", "6:05 AM"),
            ("Vinayakapuram", "6:10 AM"),
            ("Retteri", "6:15 AM"),
            ("Kolathur", "6:20 AM"),
            ("Senthil Nagar", "6:23 AM"),
            ("Padi Bridge", "6:30 AM"),
            ("Koyambedu", "6:35 AM"),
            ("Vadapalani", "6:40 AM"),
            ("Ashok Pillar", "6:43 AM"),
            ("Kasi Theatre", "6:45 AM"),
            ("Alandur Metro", "6:50 AM"),
            ("Meenambakkam", "7:00 AM"),
            ("Chrompet", "7:10 AM"),
            ("Tambaram", "7:20 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "32": {
        "vehicle_no": "TN 19 B 5497",
        "driver_name": "Ramu D.",
        "driver_phone": "73388 62194",
        "stops": [
            ("Parking Yard, Light House", "5:45 AM"),
            ("Sathya Studio", "5:50 AM"),
            ("Santhome Church", "5:55 AM"),
            ("City Centre", "6:00 AM"),
            ("Royapettah Hospital", "6:05 AM"),
            ("Meersahib Pettai", "6:10 AM"),
            ("Triplicane", "6:20 AM"),
            ("Rathna Cafe", "6:23 AM"),
            ("Walajah Road", "6:25 AM"),
            ("Ice House", "6:25 AM"),
            ("Pudupet Market", "6:30 AM"),
            ("Gemini", "6:45 AM"),
            ("Teynampet, Ilayanar Koil", "6:55 AM"),
            ("Saidapet", "7:00 AM"),
            ("Thirusulam, Airport", "7:15 AM"),
            ("Chrompet, Saravana Store", "7:25 AM"),
            ("Sanatorium Bridge", "7:30 AM"),
            ("Poondi Bazar", "7:30 AM"),
            ("MCC, East Tambaram", "7:38 AM"),
            ("Perungalathur", "7:42 AM"),
            ("Vandalur Bridge", "7:45 AM"),
            ("Karasangal", "7:48 AM"),
            ("Padappai", "7:55 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "33": {
        "vehicle_no": "TN 19 Y 0381",
        "driver_name": "Paulraj S.",
        "driver_phone": "93445 59720",
        "stops": [
            ("KVT Parking", "5:30 AM"),
            ("Brindha Theatre", "5:35 AM"),
            ("Perambur, Revathi", "5:38 AM"),
            ("D.R.B.C.C. School", "5:40 AM"),
            ("Chembiyam Police Station", "5:42 AM"),
            ("Venus Bus Stop", "5:45 AM"),
            ("Agaram Junction", "5:48 AM"),
            ("Anna Salai, Don Bosco", "5:50 AM"),
            ("Welding Shop, Paper Mills Road", "5:52 AM"),
            ("Mugambikai, Kolathur", "5:55 AM"),
            ("Rettari", "6:00 AM"),
            ("Kallikuppam", "6:15 AM"),
            ("Ambattur OT Bus Stop", "6:20 AM"),
            ("Ambattur Duclub", "6:25 AM"),
            ("Telephone Exchange", "6:28 AM"),
            ("Maduravoyal Toll", "6:35 AM"),
            ("Chettiar Vanagaram", "6:38 AM"),
            ("Porur Toll Gate", "6:42 AM"),
            ("Perungalathur", "7:30 AM"),
            ("Vandalur", "7:40 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "34": {
        "vehicle_no": "TN 22 BW 9344",
        "driver_name": "Gunasekaran K.",
        "driver_phone": "95001 84954",
        "stops": [
            ("Colours Indian School Yard", "6:45 AM"),
            ("VIT College", "6:55 AM"),
            ("Kandigai", "7:00 AM"),
            ("Kolapakkam", "7:05 AM"),
            ("Guduvanchery Market", "7:25 AM"),
            ("Guduvanchery EB", "7:28 AM"),
            ("Urapakkam Tea Shop", "7:35 AM"),
            ("Urapakkam School Stop", "7:38 AM"),
            ("Vandalur Zoo", "7:45 AM"),
            ("Manivakkam Junction", "7:50 AM"),
            ("Ruby Building", "7:55 AM"),
            ("Karasangal", "7:58 AM"),
            ("Padappai", "8:00 AM"),
            ("Salamangalam", "8:03 AM"),
            ("College", "8:10 AM"),
        ],
    },
    "35": {
        "vehicle_no": "TN 21 AF 9425",
        "driver_name": "Peachaimuthu S.",
        "driver_phone": "81221 44490",
        "stops": [
            ("Pallavaram Yard", "6:50 AM"),
            ("Pallavaram Bus Stop", "7:00 AM"),
            ("Chrompet, Saravana Store", "7:15 AM"),
            ("Sanatorium", "7:20 AM"),
            ("Tambaram, Gandhi Road", "7:25 AM"),
            ("Gulam Stop", "7:30 AM"),
            ("Krishna Nagar", "7:33 AM"),
            ("Old Perungalathur", "7:37 AM"),
            ("Mudichur, Attai Company", "7:40 AM"),
            ("Manivakkam Junction", "7:45 AM"),
            ("Ruby Building", "7:50 AM"),
            ("Karasangal", "7:53 AM"),
            ("Padappai Bus Stop", "7:55 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "36": {
        "vehicle_no": "TN 21 AF 9425",
        "driver_name": "Peachaimuthu S.",
        "driver_phone": "90948 20716",
        "stops": [
            ("Kundrathur", "6:30 AM"),
            ("Metha Nagar", "6:35 AM"),
            ("Anakaputhur", "6:40 AM"),
            ("Pammal", "6:45 AM"),
            ("Attu Thotti", "6:50 AM"),
            ("Pallavaram", "7:00 AM"),
            ("Chrompet (Ponds Company)", "7:05 AM"),
            ("Chrompet", "7:07 AM"),
            ("Tambaram Sanatorium", "7:12 AM"),
            ("Gandhi Road", "7:15 AM"),
            ("Kulum", "7:20 AM"),
            ("Krishna Nagar", "7:30 AM"),
            ("Mudichur", "7:35 AM"),
            ("Mannivakkam", "7:45 AM"),
            ("Ruby Building", "7:47 AM"),
            ("Padappai Bus Stop", "7:50 AM"),
            ("College", "8:05 AM"),
        ],
    },
    "37": {
        "vehicle_no": "TN 21 AF 9363",
        "driver_name": "Not listed",
        "driver_phone": "99622 64837",
        "stops": [
            ("Korattur, Padi, Saravana Store", "6:00 AM"),
            ("Koyambedu, Chinmaya Nagar", "6:10 AM"),
            ("Natesan Nagar, Virugambakkam", "6:15 AM"),
            ("Avichi School, Valasaravakkam", "6:20 AM"),
            ("IDFC Bank, Mega Mart, Porur", "6:25 AM"),
            ("Signal Porur Bus Stop", "6:30 AM"),
            ("Mugalivakkam, Ramapuram", "6:35 AM"),
            ("But Road", "6:37 AM"),
            ("Alandur Metro", "7:10 AM"),
            ("Tambaram", "7:25 AM"),
            ("Perungalathur", "7:30 AM"),
            ("Manivakkam Junction", "7:40 AM"),
            ("College", "8:05 AM"),
        ],
    },
}

def ask_gemini(user_question):

    bus_data = str(
        BUS_ROUTES
    )

    full_prompt = (
        SYSTEM_PROMPT
        + "\n\n"
        + "DACE BUS ROUTE DATA:\n"
        + bus_data
        + "\n\n"
        + "USER QUESTION:\n"
        + user_question
        + "\n\n"
        + "Follow the system prompt strictly. "
        + "Use only the DACE bus route data "
        + "provided above for transportation "
        + "answers. Do not invent or guess "
        + "route numbers, stops, timings, "
        + "vehicle numbers, driver names, "
        + "or phone numbers."
    )

    response = (
        client.models.generate_content(
            model="gemini-3.5-flash",
            contents=full_prompt
        )
    )

    return response.text


